name: Manifest CI

on:
  pull_request:
    paths:
      - '*.json'

permissions: {}

jobs:
  manifests:
    permissions:
      contents: read
    uses: meigma/release/.github/workflows/scoop-bucket-ci.yml@d14fb9af3ad1e43cf9aafe9e69342187af0ef0f1
