name: Manifest CI

on:
  pull_request:
    paths:
      - '*.json'

permissions: {}

jobs:
  manifests:
    permissions:
      contents: read
    uses: meigma/release/.github/workflows/scoop-bucket-ci.yml@cb43096b51b8f73e5e5df1e4f3b37bbd56f7876c
